import Foundation

/// The definitions catalog as one distributable JSON document. The
/// repository commits it (regenerated by `validate-definitions --pack`,
/// enforced by CI) and the app fetches it in bulk — one ETag-cached
/// request, so no service learns anything about the user's apps and new
/// definitions reach users without an app release.
public struct DefinitionsPack: Sendable, Codable, Hashable {
    /// Bumped only when the format changes in a way old apps cannot
    /// safely read. Unknown *fields* are already ignored by decoding.
    public static let currentSchemaVersion = 1

    public var schemaVersion: Int
    public var definitions: [AppDefinition]

    public init(definitions: [AppDefinition]) {
        self.schemaVersion = Self.currentSchemaVersion
        self.definitions = definitions.sorted { $0.bundleID < $1.bundleID }
    }

    /// Deterministic bytes — same definitions, same output — so CI can
    /// diff a fresh pack against the committed one.
    public func encoded() throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        var data = try encoder.encode(self)
        data.append(UInt8(ascii: "\n"))
        return data
    }

    /// Decodes a pack, dropping entries that do not validate — a bad
    /// remote catalog must never break scanning. Returns `nil` when the
    /// document is unreadable or from a future format.
    public static func decode(_ data: Data) -> DefinitionsPack? {
        guard var pack = try? JSONDecoder().decode(DefinitionsPack.self, from: data),
              pack.schemaVersion <= currentSchemaVersion else {
            return nil
        }
        pack.definitions = pack.definitions.filter { $0.validationProblems().isEmpty }
        return pack
    }
}
